# Generated by Django 3.2.7 on 2022-03-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=11, null=True),
        ),
    ]
